repos:
- repo: https://github.com/executablebooks/jupyter-book
  rev: v0.12.1
  hooks:
  - id: jb-to-sphinx
    args: ["olras"]
- repo: https://github.com/nschloe/betterbib
  rev: v4.2.0
  hooks:
  - id: betterbib-format
