# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Open Living Review of Andreev States
author: OLRAS Authors

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - bibliography/references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/olras/olras  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js
    - - https://cdnjs.cloudflare.com/ajax/libs/bokeh/3.2.2/bokeh.min.js
      - crossorigin: anonymous
    - - https://cdn.bokeh.org/bokeh/release/bokeh-widgets-3.2.2.min.js
      - crossorigin: anonymous
    - - https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.2.2.min.js
      - crossorigin: anonymous
    - - https://cdn.holoviz.org/panel/1.2.2-a.3/dist/panel.min.js
      - crossorigin: anonymous
    - - https://cdn.jsdelivr.net/npm/jspanel4@4.16.1/dist/jspanel.min.js
      - crossorigin: anonymous
